### ISSUE TITLE
Job not getting created

### ISSUE THREAD

**Issue by hansaya** [ressu/kube-plex#29]
I keep getting 
```[KubePlex] Bypassing kube-plex and launching original binary ```
and I do not see the jobs getting created. Is there anyway to debug this? I already set the "List of IP addresses and networks that are allowed without auth" and "kubePlex:enable:true". With that /data and /transcode mounted properly as well. On plexinc/pms-docker:latest

**Comment by hansaya** [comment]
I did more digging. If I play something that can be directly played. I see the job getting created but not for anything that requires transcording

**Comment by ressu** [comment]
Plex makes use of a feature (eae) that cannot be easily passed between pods. The kubeplex binary will skip attempting to transfer the binary in such cases.

https://github.com/ressu/kube-plex/blob/b93fe6900321d3d8137048ad4d6fdd867ae0e0ee/cmd/kube-plex/main.go#L144-L152

The error message could be clearer though, so that it was more obvious on what is happening.

**Comment by hansaya** [comment]
That make sense. I wish Plex would give us a official scalable version
